pipeline {
  agent any
    stages {
      stage ('clone code'){
        steps {
          git branch:"main", URL:"https://github.com/Mallika-Kannan/Jenkins_practice.git"
        }
      }
      stage ('Build docker image'){
        steps {
          sh 'docker build flask:latest .'
        }
      }
      stage ('Deploy with docker compose'){
        steps {
         sh 'docker compose down || true'
         sh 'docker compose up -d --build'
        }
      }
    }
}
      
      
